// Generated by gencpp from file imu_single_uwb/LinktrackNodeframe4.msg
// DO NOT EDIT!


#ifndef IMU_SINGLE_UWB_MESSAGE_LINKTRACKNODEFRAME4_H
#define IMU_SINGLE_UWB_MESSAGE_LINKTRACKNODEFRAME4_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <imu_single_uwb/LinktrackNode4Tag.h>

namespace imu_single_uwb
{
template <class ContainerAllocator>
struct LinktrackNodeframe4_
{
  typedef LinktrackNodeframe4_<ContainerAllocator> Type;

  LinktrackNodeframe4_()
    : role(0)
    , id(0)
    , local_time(0)
    , system_time(0)
    , voltage(0.0)
    , tags()  {
    }
  LinktrackNodeframe4_(const ContainerAllocator& _alloc)
    : role(0)
    , id(0)
    , local_time(0)
    , system_time(0)
    , voltage(0.0)
    , tags(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _role_type;
  _role_type role;

   typedef uint8_t _id_type;
  _id_type id;

   typedef uint32_t _local_time_type;
  _local_time_type local_time;

   typedef uint32_t _system_time_type;
  _system_time_type system_time;

   typedef float _voltage_type;
  _voltage_type voltage;

   typedef std::vector< ::imu_single_uwb::LinktrackNode4Tag_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::imu_single_uwb::LinktrackNode4Tag_<ContainerAllocator> >> _tags_type;
  _tags_type tags;





  typedef boost::shared_ptr< ::imu_single_uwb::LinktrackNodeframe4_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::imu_single_uwb::LinktrackNodeframe4_<ContainerAllocator> const> ConstPtr;

}; // struct LinktrackNodeframe4_

typedef ::imu_single_uwb::LinktrackNodeframe4_<std::allocator<void> > LinktrackNodeframe4;

typedef boost::shared_ptr< ::imu_single_uwb::LinktrackNodeframe4 > LinktrackNodeframe4Ptr;
typedef boost::shared_ptr< ::imu_single_uwb::LinktrackNodeframe4 const> LinktrackNodeframe4ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::imu_single_uwb::LinktrackNodeframe4_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::imu_single_uwb::LinktrackNodeframe4_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::imu_single_uwb::LinktrackNodeframe4_<ContainerAllocator1> & lhs, const ::imu_single_uwb::LinktrackNodeframe4_<ContainerAllocator2> & rhs)
{
  return lhs.role == rhs.role &&
    lhs.id == rhs.id &&
    lhs.local_time == rhs.local_time &&
    lhs.system_time == rhs.system_time &&
    lhs.voltage == rhs.voltage &&
    lhs.tags == rhs.tags;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::imu_single_uwb::LinktrackNodeframe4_<ContainerAllocator1> & lhs, const ::imu_single_uwb::LinktrackNodeframe4_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace imu_single_uwb

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::imu_single_uwb::LinktrackNodeframe4_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imu_single_uwb::LinktrackNodeframe4_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::imu_single_uwb::LinktrackNodeframe4_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::imu_single_uwb::LinktrackNodeframe4_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_single_uwb::LinktrackNodeframe4_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_single_uwb::LinktrackNodeframe4_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::imu_single_uwb::LinktrackNodeframe4_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f3127a55ee0f30a49a0427a969f1b3ee";
  }

  static const char* value(const ::imu_single_uwb::LinktrackNodeframe4_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf3127a55ee0f30a4ULL;
  static const uint64_t static_value2 = 0x9a0427a969f1b3eeULL;
};

template<class ContainerAllocator>
struct DataType< ::imu_single_uwb::LinktrackNodeframe4_<ContainerAllocator> >
{
  static const char* value()
  {
    return "imu_single_uwb/LinktrackNodeframe4";
  }

  static const char* value(const ::imu_single_uwb::LinktrackNodeframe4_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::imu_single_uwb::LinktrackNodeframe4_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 role\n"
"uint8 id\n"
"uint32 local_time\n"
"uint32 system_time\n"
"float32 voltage\n"
"LinktrackNode4Tag[] tags\n"
"\n"
"================================================================================\n"
"MSG: imu_single_uwb/LinktrackNode4Tag\n"
"uint8 id\n"
"float32 voltage\n"
"LinktrackNode4Anchor[] anchors\n"
"\n"
"================================================================================\n"
"MSG: imu_single_uwb/LinktrackNode4Anchor\n"
"uint8 id\n"
"float32 dis\n"
;
  }

  static const char* value(const ::imu_single_uwb::LinktrackNodeframe4_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::imu_single_uwb::LinktrackNodeframe4_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.role);
      stream.next(m.id);
      stream.next(m.local_time);
      stream.next(m.system_time);
      stream.next(m.voltage);
      stream.next(m.tags);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LinktrackNodeframe4_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::imu_single_uwb::LinktrackNodeframe4_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::imu_single_uwb::LinktrackNodeframe4_<ContainerAllocator>& v)
  {
    s << indent << "role: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.role);
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "local_time: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.local_time);
    s << indent << "system_time: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.system_time);
    s << indent << "voltage: ";
    Printer<float>::stream(s, indent + "  ", v.voltage);
    s << indent << "tags[]" << std::endl;
    for (size_t i = 0; i < v.tags.size(); ++i)
    {
      s << indent << "  tags[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::imu_single_uwb::LinktrackNode4Tag_<ContainerAllocator> >::stream(s, indent + "    ", v.tags[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // IMU_SINGLE_UWB_MESSAGE_LINKTRACKNODEFRAME4_H
