// Generated by gencpp from file imu_uwb_eskf/LinktrackNode1.msg
// DO NOT EDIT!


#ifndef IMU_UWB_ESKF_MESSAGE_LINKTRACKNODE1_H
#define IMU_UWB_ESKF_MESSAGE_LINKTRACKNODE1_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace imu_uwb_eskf
{
template <class ContainerAllocator>
struct LinktrackNode1_
{
  typedef LinktrackNode1_<ContainerAllocator> Type;

  LinktrackNode1_()
    : role(0)
    , id(0)
    , pos_3d()  {
      pos_3d.assign(0.0);
  }
  LinktrackNode1_(const ContainerAllocator& _alloc)
    : role(0)
    , id(0)
    , pos_3d()  {
  (void)_alloc;
      pos_3d.assign(0.0);
  }



   typedef uint8_t _role_type;
  _role_type role;

   typedef uint8_t _id_type;
  _id_type id;

   typedef boost::array<float, 3>  _pos_3d_type;
  _pos_3d_type pos_3d;





  typedef boost::shared_ptr< ::imu_uwb_eskf::LinktrackNode1_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::imu_uwb_eskf::LinktrackNode1_<ContainerAllocator> const> ConstPtr;

}; // struct LinktrackNode1_

typedef ::imu_uwb_eskf::LinktrackNode1_<std::allocator<void> > LinktrackNode1;

typedef boost::shared_ptr< ::imu_uwb_eskf::LinktrackNode1 > LinktrackNode1Ptr;
typedef boost::shared_ptr< ::imu_uwb_eskf::LinktrackNode1 const> LinktrackNode1ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::imu_uwb_eskf::LinktrackNode1_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::imu_uwb_eskf::LinktrackNode1_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::imu_uwb_eskf::LinktrackNode1_<ContainerAllocator1> & lhs, const ::imu_uwb_eskf::LinktrackNode1_<ContainerAllocator2> & rhs)
{
  return lhs.role == rhs.role &&
    lhs.id == rhs.id &&
    lhs.pos_3d == rhs.pos_3d;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::imu_uwb_eskf::LinktrackNode1_<ContainerAllocator1> & lhs, const ::imu_uwb_eskf::LinktrackNode1_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace imu_uwb_eskf

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::imu_uwb_eskf::LinktrackNode1_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imu_uwb_eskf::LinktrackNode1_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::imu_uwb_eskf::LinktrackNode1_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::imu_uwb_eskf::LinktrackNode1_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_uwb_eskf::LinktrackNode1_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_uwb_eskf::LinktrackNode1_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::imu_uwb_eskf::LinktrackNode1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d132fffb83ae82e5909718b6a85eaccc";
  }

  static const char* value(const ::imu_uwb_eskf::LinktrackNode1_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd132fffb83ae82e5ULL;
  static const uint64_t static_value2 = 0x909718b6a85eacccULL;
};

template<class ContainerAllocator>
struct DataType< ::imu_uwb_eskf::LinktrackNode1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "imu_uwb_eskf/LinktrackNode1";
  }

  static const char* value(const ::imu_uwb_eskf::LinktrackNode1_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::imu_uwb_eskf::LinktrackNode1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 role\n"
"uint8 id\n"
"float32[3] pos_3d\n"
;
  }

  static const char* value(const ::imu_uwb_eskf::LinktrackNode1_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::imu_uwb_eskf::LinktrackNode1_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.role);
      stream.next(m.id);
      stream.next(m.pos_3d);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LinktrackNode1_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::imu_uwb_eskf::LinktrackNode1_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::imu_uwb_eskf::LinktrackNode1_<ContainerAllocator>& v)
  {
    s << indent << "role: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.role);
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "pos_3d[]" << std::endl;
    for (size_t i = 0; i < v.pos_3d.size(); ++i)
    {
      s << indent << "  pos_3d[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.pos_3d[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // IMU_UWB_ESKF_MESSAGE_LINKTRACKNODE1_H
