// Generated by gencpp from file imu_uwb_eskf/TofsenseCascade.msg
// DO NOT EDIT!


#ifndef IMU_UWB_ESKF_MESSAGE_TOFSENSECASCADE_H
#define IMU_UWB_ESKF_MESSAGE_TOFSENSECASCADE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <imu_uwb_eskf/TofsenseFrame0.h>

namespace imu_uwb_eskf
{
template <class ContainerAllocator>
struct TofsenseCascade_
{
  typedef TofsenseCascade_<ContainerAllocator> Type;

  TofsenseCascade_()
    : nodes()  {
    }
  TofsenseCascade_(const ContainerAllocator& _alloc)
    : nodes(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::imu_uwb_eskf::TofsenseFrame0_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::imu_uwb_eskf::TofsenseFrame0_<ContainerAllocator> >> _nodes_type;
  _nodes_type nodes;





  typedef boost::shared_ptr< ::imu_uwb_eskf::TofsenseCascade_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::imu_uwb_eskf::TofsenseCascade_<ContainerAllocator> const> ConstPtr;

}; // struct TofsenseCascade_

typedef ::imu_uwb_eskf::TofsenseCascade_<std::allocator<void> > TofsenseCascade;

typedef boost::shared_ptr< ::imu_uwb_eskf::TofsenseCascade > TofsenseCascadePtr;
typedef boost::shared_ptr< ::imu_uwb_eskf::TofsenseCascade const> TofsenseCascadeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::imu_uwb_eskf::TofsenseCascade_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::imu_uwb_eskf::TofsenseCascade_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::imu_uwb_eskf::TofsenseCascade_<ContainerAllocator1> & lhs, const ::imu_uwb_eskf::TofsenseCascade_<ContainerAllocator2> & rhs)
{
  return lhs.nodes == rhs.nodes;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::imu_uwb_eskf::TofsenseCascade_<ContainerAllocator1> & lhs, const ::imu_uwb_eskf::TofsenseCascade_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace imu_uwb_eskf

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::imu_uwb_eskf::TofsenseCascade_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imu_uwb_eskf::TofsenseCascade_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::imu_uwb_eskf::TofsenseCascade_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::imu_uwb_eskf::TofsenseCascade_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_uwb_eskf::TofsenseCascade_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_uwb_eskf::TofsenseCascade_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::imu_uwb_eskf::TofsenseCascade_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e254ff763c3396ff0c54cf33bd09b21b";
  }

  static const char* value(const ::imu_uwb_eskf::TofsenseCascade_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe254ff763c3396ffULL;
  static const uint64_t static_value2 = 0x0c54cf33bd09b21bULL;
};

template<class ContainerAllocator>
struct DataType< ::imu_uwb_eskf::TofsenseCascade_<ContainerAllocator> >
{
  static const char* value()
  {
    return "imu_uwb_eskf/TofsenseCascade";
  }

  static const char* value(const ::imu_uwb_eskf::TofsenseCascade_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::imu_uwb_eskf::TofsenseCascade_<ContainerAllocator> >
{
  static const char* value()
  {
    return "TofsenseFrame0[] nodes\n"
"\n"
"================================================================================\n"
"MSG: imu_uwb_eskf/TofsenseFrame0\n"
"uint8 id\n"
"uint32 system_time\n"
"float32 dis\n"
"uint8 dis_status\n"
"uint16 signal_strength\n"
"uint8 range_precision\n"
;
  }

  static const char* value(const ::imu_uwb_eskf::TofsenseCascade_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::imu_uwb_eskf::TofsenseCascade_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.nodes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TofsenseCascade_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::imu_uwb_eskf::TofsenseCascade_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::imu_uwb_eskf::TofsenseCascade_<ContainerAllocator>& v)
  {
    s << indent << "nodes[]" << std::endl;
    for (size_t i = 0; i < v.nodes.size(); ++i)
    {
      s << indent << "  nodes[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::imu_uwb_eskf::TofsenseFrame0_<ContainerAllocator> >::stream(s, indent + "    ", v.nodes[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // IMU_UWB_ESKF_MESSAGE_TOFSENSECASCADE_H
